### ISSUE TITLE
Design decision: should we use RxJS?

### ISSUE THREAD

**Issue by JonasVautherin** [mavlink/MAVSDK-JavaScript#3]
We need to decide what technology we want to use for this project. Geoff was mentioning RxJS.

Let's discuss that here!

**Comment by JonasVautherin** [comment]
@flatlevel, @mrpollo: FYI

**Comment by mrpollo** [comment]
Here are some very high-level goals I think this project should have

- Import friendly, only consume what you need
- Modern JS (ES6>) or Typescript (either via definition file or full ts)
- Allow transpiling as a post-process
- Targeted towards React, Vue, AngularJS developers, compatibility with Redux and Vuex is paramount

Using RxJS should be fine as long as we can find the right way to implement it, currently, the auto-generated JS from gRPC-web is a closure-based api that is very limiting in terms of how you can access the data, it would be worthwhile investigating if RxJS can help with this.

I can help bring anyone interested up to speed.

**Comment by unipheas** [comment]
I quite like RxJS so I'm for this idea. I'm also for Typescript as it's a typed language and keeps everything more organized.

**Comment by unipheas** [comment]
I'm working on this now. We can probably close this.
